/* Generated C bindings for dotlottie-rs */

#ifndef DOTLOTTIE_PLAYER_H
#define DOTLOTTIE_PLAYER_H

/* Generated with cbindgen:0.29.2 */

/* Warning, this file is autogenerated. Do not modify this! */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
/* Type aliases for cleaner C code */
typedef struct dotlottiePlayer DotLottiePlayer;
typedef struct dotlottieDotLottieConfig DotLottieConfig;
#define DOTLOTTIE_SUCCESS 0


typedef enum dotlottieDotLottieResult {
  Success = 0,
  Error = 1,
  InvalidParameter = 2,
  ManifestNotAvailable = 3,
  AnimationNotLoaded = 4,
  InsufficientCondition = 5,
  FeatureNotEnabled = 6,
} dotlottieDotLottieResult;

typedef enum dotlottieMode {
  Forward,
  Reverse,
  Bounce,
  ReverseBounce,
} dotlottieMode;

typedef enum dotlottieFit {
  Contain,
  Fill,
  Cover,
  FitWidth,
  FitHeight,
  None,
} dotlottieFit;

typedef enum dotlottiePlaybackStatus {
  Playing = 0,
  Paused = 1,
  Stopped = 2,
} dotlottiePlaybackStatus;

typedef enum dotlottieColorSpace {
  ABGR8888,
  ABGR8888S,
  ARGB8888,
  ARGB8888S,
} dotlottieColorSpace;

typedef enum dotlottieDotLottieWgpuTargetType {
  Surface = 0,
  Texture = 1,
} dotlottieDotLottieWgpuTargetType;

typedef enum dotlottieDotLottiePlayerEventType {
  Load = 0,
  LoadError = 1,
  Play = 2,
  Pause = 3,
  Stop = 4,
  Frame = 5,
  Render = 6,
  Loop = 7,
  Complete = 8,
} dotlottieDotLottiePlayerEventType;

typedef enum dotlottieStateMachineEventType {
  StateMachineStart = 0,
  StateMachineStop = 1,
  StateMachineTransition = 2,
  StateMachineStateEntered = 3,
  StateMachineStateExit = 4,
  StateMachineCustomEvent = 5,
  StateMachineError = 6,
  StateMachineStringInputChange = 7,
  StateMachineNumericInputChange = 8,
  StateMachineBooleanInputChange = 9,
  StateMachineInputFired = 10,
} dotlottieStateMachineEventType;

/**
 * Opaque C-facing wrapper for StateMachineEngine.
 * Always present; inner is only populated with state-machines feature.
 * Load functions return null_mut() when state-machines is off, so C callers
 * will never hold a valid (non-null) pointer when the feature is disabled.
 */
typedef struct dotlottieDotLottieStateMachine dotlottieDotLottieStateMachine;

typedef struct dotlottiePlayer dotlottiePlayer;

typedef struct dotlottieRgba dotlottieRgba;

typedef struct dotlottieLayout {
  enum dotlottieFit fit;
  float align[2];
} dotlottieLayout;

typedef union dotlottieDotLottiePlayerEventData {
  float frame_no;
  uint32_t loop_count;
} dotlottieDotLottiePlayerEventData;

typedef struct dotlottieDotLottiePlayerEvent {
  enum dotlottieDotLottiePlayerEventType event_type;
  union dotlottieDotLottiePlayerEventData data;
} dotlottieDotLottiePlayerEvent;

typedef enum dotlottiePlayerEvent_Tag {
  PointerDown,
  PointerUp,
  PointerMove,
  PointerEnter,
  PointerExit,
  Click,
  OnComplete,
  OnLoopComplete,
} dotlottiePlayerEvent_Tag;

typedef struct dotlottiePointerDown_Body {
  float x;
  float y;
} dotlottiePointerDown_Body;

typedef struct dotlottiePointerUp_Body {
  float x;
  float y;
} dotlottiePointerUp_Body;

typedef struct dotlottiePointerMove_Body {
  float x;
  float y;
} dotlottiePointerMove_Body;

typedef struct dotlottiePointerEnter_Body {
  float x;
  float y;
} dotlottiePointerEnter_Body;

typedef struct dotlottiePointerExit_Body {
  float x;
  float y;
} dotlottiePointerExit_Body;

typedef struct dotlottieClick_Body {
  float x;
  float y;
} dotlottieClick_Body;

typedef struct dotlottiePlayerEvent {
  dotlottiePlayerEvent_Tag tag;
  union {
    dotlottiePointerDown_Body pointer_down;
    dotlottiePointerUp_Body pointer_up;
    dotlottiePointerMove_Body pointer_move;
    dotlottiePointerEnter_Body pointer_enter;
    dotlottiePointerExit_Body pointer_exit;
    dotlottieClick_Body click;
  };
} dotlottiePlayerEvent;

/**
 * Transition event data with pointers to state names
 */
typedef struct dotlottieStateMachineTransitionData {
  const char *previous_state;
  const char *new_state;
} dotlottieStateMachineTransitionData;

/**
 * State event data (for StateEntered/StateExit)
 */
typedef struct dotlottieStateMachineStateData {
  const char *state;
} dotlottieStateMachineStateData;

/**
 * Message event data (for CustomEvent/Error)
 */
typedef struct dotlottieStateMachineMessageData {
  const char *message;
} dotlottieStateMachineMessageData;

/**
 * String input change event data
 */
typedef struct dotlottieStateMachineStringInputData {
  const char *name;
  const char *old_value;
  const char *new_value;
} dotlottieStateMachineStringInputData;

/**
 * Numeric input change event data
 */
typedef struct dotlottieStateMachineNumericInputData {
  const char *name;
  float old_value;
  float new_value;
} dotlottieStateMachineNumericInputData;

/**
 * Boolean input change event data
 */
typedef struct dotlottieStateMachineBooleanInputData {
  const char *name;
  bool old_value;
  bool new_value;
} dotlottieStateMachineBooleanInputData;

/**
 * Input fired event data
 */
typedef struct dotlottieStateMachineInputFiredData {
  const char *name;
} dotlottieStateMachineInputFiredData;

/**
 * Union of all possible state machine event data types
 */
typedef union dotlottieStateMachineEventData {
  struct dotlottieStateMachineTransitionData transition;
  struct dotlottieStateMachineStateData state;
  struct dotlottieStateMachineMessageData message;
  struct dotlottieStateMachineStringInputData string_input;
  struct dotlottieStateMachineNumericInputData numeric_input;
  struct dotlottieStateMachineBooleanInputData boolean_input;
  struct dotlottieStateMachineInputFiredData input_fired;
} dotlottieStateMachineEventData;

/**
 * State machine event with type tag and data union.
 * String pointers are valid until the next poll call.
 */
typedef struct dotlottieStateMachineEvent {
  enum dotlottieStateMachineEventType event_type;
  union dotlottieStateMachineEventData data;
} dotlottieStateMachineEvent;

/**
 * Internal state machine event (for framework use).
 * The message pointer is valid until the next poll call.
 */
typedef struct dotlottieStateMachineInternalEvent {
  const char *message;
} dotlottieStateMachineInternalEvent;



#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

struct dotlottiePlayer *dotlottie_new_player(uint32_t threads);

enum dotlottieDotLottieResult dotlottie_load_font(const char *name,
                                                  const uint8_t *data,
                                                  uintptr_t size);

enum dotlottieDotLottieResult dotlottie_unload_font(const char *name);

enum dotlottieDotLottieResult dotlottie_destroy(struct dotlottiePlayer *ptr);

enum dotlottieDotLottieResult dotlottie_load_animation_data(struct dotlottiePlayer *ptr,
                                                            const char *animation_data);

enum dotlottieDotLottieResult dotlottie_load_animation_path(struct dotlottiePlayer *ptr,
                                                            const char *animation_path);

enum dotlottieDotLottieResult dotlottie_load_animation(struct dotlottiePlayer *ptr,
                                                       const char *animation_id);

enum dotlottieDotLottieResult dotlottie_load_dotlottie_data(struct dotlottiePlayer *ptr,
                                                            const char *file_data,
                                                            uintptr_t file_size);

/**
 * Get the manifest as a JSON string.
 *
 * # Parameters
 * - `ptr`: Pointer to the Player instance
 * - `buffer`: Buffer to store the JSON, or NULL to query required size
 * - `size_out`: Pointer to receive the required buffer size (including null terminator)
 *
 * # Returns
 * - `DotLottieResult::Success` on success
 * - `DotLottieResult::ManifestNotAvailable` if no manifest is available
 * - `DotLottieResult::InvalidParameter` if ptr is invalid
 * - `DotLottieResult::FeatureNotEnabled` if built without the `dotlottie` feature
 * - `DotLottieResult::Error` if the manifest cannot be serialized to JSON
 */
enum dotlottieDotLottieResult dotlottie_get_manifest(struct dotlottiePlayer *ptr,
                                                     char *buffer,
                                                     uintptr_t *size_out);

enum dotlottieDotLottieResult dotlottie_set_mode(struct dotlottiePlayer *ptr,
                                                 enum dotlottieMode mode);

enum dotlottieDotLottieResult dotlottie_set_speed(struct dotlottiePlayer *ptr, float speed);

enum dotlottieDotLottieResult dotlottie_set_loop(struct dotlottiePlayer *ptr, bool loop_animation);

enum dotlottieDotLottieResult dotlottie_set_loop_count(struct dotlottiePlayer *ptr,
                                                       uint32_t loop_count);

enum dotlottieDotLottieResult dotlottie_set_autoplay(struct dotlottiePlayer *ptr, bool autoplay);

enum dotlottieDotLottieResult dotlottie_set_use_frame_interpolation(struct dotlottiePlayer *ptr,
                                                                    bool enabled);

enum dotlottieDotLottieResult dotlottie_set_background(struct dotlottiePlayer *ptr,
                                                       uint8_t r,
                                                       uint8_t g,
                                                       uint8_t b,
                                                       uint8_t a);

/**
 * Sets the playback segment for the animation.
 *
 * # Parameters
 * - `ptr`: Pointer to the Player instance
 * - `segment`: Pointer to an array of 2 floats [start_frame, end_frame], or NULL to clear
 *
 * # Returns
 * - `DotLottieResult::Success` on success
 * - `DotLottieResult::InvalidParameter` if the player pointer is invalid
 */
enum dotlottieDotLottieResult dotlottie_set_segment(struct dotlottiePlayer *ptr,
                                                    const float (*segment)[2]);

/**
 * Sets the active marker for the animation.
 *
 * # Parameters
 * - `ptr`: Pointer to the Player instance
 * - `marker`: Pointer to a null-terminated C string with the marker name, or NULL to clear
 *
 * # Returns
 * - `DotLottieResult::Success` on success
 * - `DotLottieResult::InvalidParameter` if the player pointer is invalid
 */
enum dotlottieDotLottieResult dotlottie_set_marker(struct dotlottiePlayer *ptr, const char *marker);

/**
 * Sets the layout configuration for the animation.
 *
 * # Parameters
 * - `ptr`: Pointer to the Player instance
 * - `layout`: Layout configuration (fit mode and alignment)
 *
 * # Returns
 * - `DotLottieResult::Success` on success
 * - `DotLottieResult::InvalidParameter` if the player pointer is invalid
 */
enum dotlottieDotLottieResult dotlottie_set_layout(struct dotlottiePlayer *ptr,
                                                   struct dotlottieLayout layout);

/**
 * Returns the current playback mode.
 *
 * # Parameters
 * - `ptr`: Pointer to the Player instance
 *
 * # Returns
 * The current Mode, or Mode::Forward if the pointer is invalid
 */
enum dotlottieMode dotlottie_get_mode(struct dotlottiePlayer *ptr);

/**
 * Returns the current playback speed.
 *
 * # Parameters
 * - `ptr`: Pointer to the Player instance
 *
 * # Returns
 * The current speed multiplier, or 1.0 if the pointer is invalid
 */
float dotlottie_get_speed(struct dotlottiePlayer *ptr);

/**
 * Returns whether looping is enabled.
 *
 * # Parameters
 * - `ptr`: Pointer to the Player instance
 *
 * # Returns
 * true if looping is enabled, false otherwise or if the pointer is invalid
 */
bool dotlottie_get_loop(struct dotlottiePlayer *ptr);

/**
 * Returns the configured loop count (0 = infinite).
 *
 * # Parameters
 * - `ptr`: Pointer to the Player instance
 *
 * # Returns
 * The configured loop count, or 0 if the pointer is invalid
 */
uint32_t dotlottie_get_loop_count(struct dotlottiePlayer *ptr);

/**
 * Returns whether autoplay is enabled.
 *
 * # Parameters
 * - `ptr`: Pointer to the Player instance
 *
 * # Returns
 * true if autoplay is enabled, false otherwise or if the pointer is invalid
 */
bool dotlottie_get_autoplay(struct dotlottiePlayer *ptr);

/**
 * Returns whether frame interpolation is enabled.
 *
 * # Parameters
 * - `ptr`: Pointer to the Player instance
 *
 * # Returns
 * true if frame interpolation is enabled, false otherwise or if the pointer is invalid
 */
bool dotlottie_get_use_frame_interpolation(struct dotlottiePlayer *ptr);

enum dotlottieDotLottieResult dotlottie_get_background(struct dotlottiePlayer *ptr,
                                                       uint8_t *r,
                                                       uint8_t *g,
                                                       uint8_t *b,
                                                       uint8_t *a);

/**
 * Returns the current segment.
 *
 * # Parameters
 * - `ptr`: Pointer to the Player instance
 * - `result`: Pointer to a [f32; 2] array to store [start_frame, end_frame]
 *
 * # Returns
 * - `DotLottieResult::Success` if segment exists and was copied
 * - `DotLottieResult::InvalidParameter` if pointers are invalid or no segment is set
 */
enum dotlottieDotLottieResult dotlottie_get_segment(struct dotlottiePlayer *ptr,
                                                    float (*result)[2]);

/**
 * Returns the current marker name.
 *
 * # Parameters
 * - `ptr`: Pointer to the Player instance
 * - `buffer`: Buffer to store the marker name, or NULL to query required size
 * - `size_out`: Pointer to receive the required buffer size (including null terminator)
 *
 * # Usage
 * ```c
 * size_t size;
 * dotlottie_get_active_marker(player, NULL, &size);  // get required size
 * char* buf = malloc(size);
 * dotlottie_get_active_marker(player, buf, NULL);    // get string
 * ```
 *
 * # Returns
 * - `DotLottieResult::Success` on success
 * - `DotLottieResult::InvalidParameter` if no marker is set or player pointer is invalid
 */
enum dotlottieDotLottieResult dotlottie_get_active_marker(struct dotlottiePlayer *ptr,
                                                          char *buffer,
                                                          uintptr_t *size_out);

enum dotlottieDotLottieResult dotlottie_get_layout(struct dotlottiePlayer *ptr,
                                                   struct dotlottieLayout *result);

enum dotlottieDotLottieResult dotlottie_get_total_frames(struct dotlottiePlayer *ptr,
                                                         float *result);

enum dotlottieDotLottieResult dotlottie_get_duration(struct dotlottiePlayer *ptr, float *result);

enum dotlottieDotLottieResult dotlottie_get_current_frame(struct dotlottiePlayer *ptr,
                                                          float *result);

enum dotlottieDotLottieResult dotlottie_get_current_loop_count(struct dotlottiePlayer *ptr,
                                                               uint32_t *result);

/**
 * Returns whether an animation is loaded.
 */
bool dotlottie_is_loaded(struct dotlottiePlayer *ptr);

/**
 * Returns the current playback status.
 *
 * Priority order: Playing > Paused > Stopped
 *
 * # Parameters
 * - `ptr`: Pointer to the Player instance
 *
 * # Returns
 * The current PlaybackStatus (Playing, Paused, or Stopped)
 * Returns Stopped if the pointer is invalid
 */
enum dotlottiePlaybackStatus dotlottie_get_playback_status(struct dotlottiePlayer *ptr);

enum dotlottieDotLottieResult dotlottie_play(struct dotlottiePlayer *ptr);

enum dotlottieDotLottieResult dotlottie_pause(struct dotlottiePlayer *ptr);

enum dotlottieDotLottieResult dotlottie_stop(struct dotlottiePlayer *ptr);

enum dotlottieDotLottieResult dotlottie_set_audio_volume(struct dotlottiePlayer *ptr, float volume);

enum dotlottieDotLottieResult dotlottie_get_audio_volume(struct dotlottiePlayer *ptr,
                                                         float *result);

enum dotlottieDotLottieResult dotlottie_set_frame(struct dotlottiePlayer *ptr, float no);

enum dotlottieDotLottieResult dotlottie_render(struct dotlottiePlayer *ptr);

/**
 * Advance the animation by `dt` seconds and render if the frame changed.
 *
 * If `rendered` is non-null, writes `true` when a new frame was rendered
 * and `false` when the frame was unchanged.
 *
 * Example of the usage
 * ```c
 *     double last = get_time_ms();
 *     bool rendered;
 *     while(true) {
 *       double now = get_time_ms();
 *       float dt = (float)(now - last);
 *       last = now;
 *       dotlottie_tick(player, dt, &rendered);
 *       if (rendered) display(buffer, width, height);
 *     }
 * ```
 */
enum dotlottieDotLottieResult dotlottie_tick(struct dotlottiePlayer *ptr, float dt, bool *rendered);

/**
 * Returns whether the animation has completed playback.
 */
bool dotlottie_is_complete(struct dotlottiePlayer *ptr);

/**
 * Sets the software rendering target.
 *
 * # Parameters
 * - `ptr`: Pointer to the Player instance
 * - `buffer`: Pointer to the pixel buffer (must be width * height in size)
 * - `width`: Width of the buffer in pixels
 * - `height`: Height of the buffer in pixels
 * - `color_space`: Color space for the buffer
 *
 * # Returns
 * - `DotLottieResult::Success` on success
 * - `DotLottieResult::InvalidParameter` if buffer is too small or pointer is invalid
 */
enum dotlottieDotLottieResult dotlottie_set_sw_target(struct dotlottiePlayer *ptr,
                                                      uint32_t *buffer,
                                                      uint32_t width,
                                                      uint32_t height,
                                                      enum dotlottieColorSpace color_space);

enum dotlottieDotLottieResult dotlottie_set_gl_target(struct dotlottiePlayer *ptr,
                                                      void *display,
                                                      void *surface,
                                                      void *context,
                                                      int32_t id,
                                                      uint32_t width,
                                                      uint32_t height);

enum dotlottieDotLottieResult dotlottie_set_wg_target(struct dotlottiePlayer *ptr,
                                                      void *device,
                                                      void *instance,
                                                      void *target,
                                                      uint32_t width,
                                                      uint32_t height,
                                                      enum dotlottieDotLottieWgpuTargetType target_type);

enum dotlottieDotLottieResult dotlottie_set_theme(struct dotlottiePlayer *ptr,
                                                  const char *theme_id);

enum dotlottieDotLottieResult dotlottie_reset_theme(struct dotlottiePlayer *ptr);

/**
 * Sets the theme using raw theme data.
 *
 * # Parameters
 * - `ptr`: Pointer to the Player instance
 * - `theme_data`: Null-terminated C string containing the theme JSON data
 *
 * # Returns
 * - `DotLottieResult::Success` on success
 * - `DotLottieResult::FeatureNotEnabled` if built without the `theming` feature
 * - `DotLottieResult::InvalidParameter` if the data is invalid or pointer is invalid
 */
enum dotlottieDotLottieResult dotlottie_set_theme_data(struct dotlottiePlayer *ptr,
                                                       const char *theme_data);

/**
 * Set slots using a JSON string
 *
 * This is the most flexible way to set slots, supporting all slot types
 * including complex gradients and animated keyframes.
 *
 * # Example JSON format
 * ```json
 * {
 *     "color_slot_id": {"p": {"a": 0, "k": [1.0, 0.0, 0.0]}},
 *     "text_slot_id": {"p": {"k": [{"t": 0, "s": {"t": "Hello"}}]}}
 * }
 * ```
 */
enum dotlottieDotLottieResult dotlottie_set_slots_str(struct dotlottiePlayer *ptr,
                                                      const char *slots_json);

/**
 * Clear all slots
 */
enum dotlottieDotLottieResult dotlottie_clear_slots(struct dotlottiePlayer *ptr);

/**
 * Clear a specific slot by ID
 */
enum dotlottieDotLottieResult dotlottie_clear_slot(struct dotlottiePlayer *ptr,
                                                   const char *slot_id);

/**
 * Set a color slot with RGB values (0.0 to 1.0)
 */
enum dotlottieDotLottieResult dotlottie_set_color_slot(struct dotlottiePlayer *ptr,
                                                       const char *slot_id,
                                                       float r,
                                                       float g,
                                                       float b);

/**
 * Set a scalar slot with a single float value
 */
enum dotlottieDotLottieResult dotlottie_set_scalar_slot(struct dotlottiePlayer *ptr,
                                                        const char *slot_id,
                                                        float value);

/**
 * Set a text slot with a text string
 */
enum dotlottieDotLottieResult dotlottie_set_text_slot(struct dotlottiePlayer *ptr,
                                                      const char *slot_id,
                                                      const char *text);

/**
 * Set a 2D vector slot
 */
enum dotlottieDotLottieResult dotlottie_set_vector_slot(struct dotlottiePlayer *ptr,
                                                        const char *slot_id,
                                                        float x,
                                                        float y);

/**
 * Set a 2D position slot
 */
enum dotlottieDotLottieResult dotlottie_set_position_slot(struct dotlottiePlayer *ptr,
                                                          const char *slot_id,
                                                          float x,
                                                          float y);

/**
 * Set an image slot from a file path
 */
enum dotlottieDotLottieResult dotlottie_set_image_slot_path(struct dotlottiePlayer *ptr,
                                                            const char *slot_id,
                                                            const char *path);

/**
 * Set an image slot from a data URL (base64 encoded)
 */
enum dotlottieDotLottieResult dotlottie_set_image_slot_data_url(struct dotlottiePlayer *ptr,
                                                                const char *slot_id,
                                                                const char *data_url);

/**
 * Returns the number of slot IDs in the current animation.
 */
enum dotlottieDotLottieResult dotlottie_get_slot_ids_count(struct dotlottiePlayer *ptr,
                                                           uint32_t *count);

/**
 * Returns a slot ID by index.
 *
 * Call `dotlottie_get_slot_ids_count` first to know how many IDs exist.
 * Pass `buffer = NULL` to query the required size via `size_out`.
 */
enum dotlottieDotLottieResult dotlottie_get_slot_id(struct dotlottiePlayer *ptr,
                                                    uint32_t index,
                                                    char *buffer,
                                                    uintptr_t *size_out);

/**
 * Returns the type name of a slot (e.g., "color", "scalar", "text").
 *
 * Pass `buffer = NULL` to query the required size via `size_out`.
 */
enum dotlottieDotLottieResult dotlottie_get_slot_type(struct dotlottiePlayer *ptr,
                                                      const char *slot_id,
                                                      char *buffer,
                                                      uintptr_t *size_out);

/**
 * Returns a slot value as a JSON string.
 *
 * Pass `buffer = NULL` to query the required size via `size_out`.
 */
enum dotlottieDotLottieResult dotlottie_get_slot_str(struct dotlottiePlayer *ptr,
                                                     const char *slot_id,
                                                     char *buffer,
                                                     uintptr_t *size_out);

/**
 * Returns all slots as a JSON string.
 *
 * Pass `buffer = NULL` to query the required size via `size_out`.
 */
enum dotlottieDotLottieResult dotlottie_get_slots_str(struct dotlottiePlayer *ptr,
                                                      char *buffer,
                                                      uintptr_t *size_out);

/**
 * Set a slot value from a JSON string.
 *
 * The slot must already exist (i.e., its ID must be in the current slot values).
 * The JSON should match the format for the slot's type.
 */
enum dotlottieDotLottieResult dotlottie_set_slot_str(struct dotlottiePlayer *ptr,
                                                     const char *slot_id,
                                                     const char *json);

/**
 * Reset a single slot to its default value (from the animation).
 */
enum dotlottieDotLottieResult dotlottie_reset_slot(struct dotlottiePlayer *ptr,
                                                   const char *slot_id);

/**
 * Reset all slots to their default values (from the animation).
 */
enum dotlottieDotLottieResult dotlottie_reset_slots(struct dotlottiePlayer *ptr);

/**
 * Gets the number of markers in the current animation.
 *
 * # Parameters
 * - `ptr`: Pointer to the Player instance
 * - `count`: Pointer to receive the marker count
 *
 * # Returns
 * - `DOTLOTTIE_SUCCESS` on success
 * - `DOTLOTTIE_INVALID_PARAMETER` if pointers are null
 */
enum dotlottieDotLottieResult dotlottie_get_markers_count(struct dotlottiePlayer *ptr,
                                                          uint32_t *count);

/**
 * Gets a marker by index.
 *
 * # Parameters
 * - `ptr`: Pointer to the Player instance
 * - `idx`: Index of the marker (0-based)
 * - `name`: Pointer to receive the marker name (library-owned, do not free)
 * - `start`: Pointer to receive the marker start frame, or NULL to skip
 * - `end`: Pointer to receive the marker end frame, or NULL to skip
 *
 * # Returns
 * - `DOTLOTTIE_SUCCESS` on success
 * - `DOTLOTTIE_INVALID_PARAMETER` if ptr/name is null or index is out of bounds
 */
enum dotlottieDotLottieResult dotlottie_get_marker(struct dotlottiePlayer *ptr,
                                                   uint32_t idx,
                                                   const char **name,
                                                   float *start,
                                                   float *end);

/**
 * Returns the active animation ID.
 *
 * # Parameters
 * - `ptr`: Pointer to the Player instance
 * - `buffer`: Buffer to store the ID, or NULL to query required size
 * - `size_out`: Pointer to receive the required buffer size (including null terminator)
 *
 * # Returns
 * - `DotLottieResult::Success` on success
 * - `DotLottieResult::FeatureNotEnabled` if built without the `dotlottie` feature
 * - `DotLottieResult::InvalidParameter` if no animation is active or player pointer is invalid
 */
enum dotlottieDotLottieResult dotlottie_get_animation_id(struct dotlottiePlayer *ptr,
                                                         char *buffer,
                                                         uintptr_t *size_out);

/**
 * Returns the active theme ID.
 *
 * # Parameters
 * - `ptr`: Pointer to the Player instance
 * - `buffer`: Buffer to store the ID, or NULL to query required size
 * - `size_out`: Pointer to receive the required buffer size (including null terminator)
 *
 * # Returns
 * - `DotLottieResult::Success` on success
 * - `DotLottieResult::FeatureNotEnabled` if built without the `theming` feature
 * - `DotLottieResult::InvalidParameter` if no theme is active or player pointer is invalid
 */
enum dotlottieDotLottieResult dotlottie_get_theme_id(struct dotlottiePlayer *ptr,
                                                     char *buffer,
                                                     uintptr_t *size_out);

enum dotlottieDotLottieResult dotlottie_set_viewport(struct dotlottiePlayer *ptr,
                                                     int32_t x,
                                                     int32_t y,
                                                     int32_t w,
                                                     int32_t h);

enum dotlottieDotLottieResult dotlottie_get_animation_size(struct dotlottiePlayer *ptr,
                                                           float *picture_width,
                                                           float *picture_height);

/**
 * Poll for the next player event from the event queue
 *
 * Returns 1 if an event was retrieved, 0 if no events are available, or -1 on error.
 * The event data is written to the event pointer.
 *
 * # Example
 * ```c
 * DotLottiePlayerEvent event;
 * while (dotlottie_poll_event(player, &event) == 1) {
 *     switch (event.event_type) {
 *         case DotLottiePlayerEventType_Load:
 *             printf("Animation loaded\n");
 *             break;
 *         case DotLottiePlayerEventType_Frame:
 *             printf("Frame: %f\n", event.data.frame_no);
 *             break;
 *     }
 * }
 * ```
 */
int32_t dotlottie_poll_event(struct dotlottiePlayer *player,
                             struct dotlottieDotLottiePlayerEvent *event);

/**
 * Load a state machine by ID from the loaded .lottie file
 *
 * Returns a pointer to the StateMachineEngine or NULL on error.
 * The returned state machine borrows the runtime - runtime cannot be destroyed
 * while the state machine exists.
 *
 * # Safety
 * - Runtime pointer must be valid
 * - Returned state machine must be destroyed with dotlottie_state_machine_release()
 *   BEFORE destroying the runtime
 */
struct dotlottieDotLottieStateMachine *dotlottie_state_machine_load(struct dotlottiePlayer *runtime,
                                                                    const char *state_machine_id);

/**
 * Load a state machine from a JSON definition string
 *
 * Returns a pointer to the StateMachineEngine or NULL on error.
 */
struct dotlottieDotLottieStateMachine *dotlottie_state_machine_load_data(struct dotlottiePlayer *runtime,
                                                                         const char *state_machine_definition);

/**
 * Start the state machine with the specified URL policy.
 *
 * # Parameters
 * - `sm`: Pointer to the StateMachineEngine instance
 * - `whitelist`: Comma-separated list of allowed URL patterns (or NULL for empty)
 * - `require_user_interaction`: Whether user interaction is required before opening URLs
 *
 * # Returns
 * DotLottieResult::Success if started, error variant if failed
 * - `DotLottieResult::FeatureNotEnabled` if built without the `state-machines` feature
 */
enum dotlottieDotLottieResult dotlottie_state_machine_start(struct dotlottieDotLottieStateMachine *sm,
                                                            const char *whitelist,
                                                            bool require_user_interaction);

/**
 * Stop the state machine (does not release the borrow)
 *
 * Call dotlottie_state_machine_release() to actually destroy the state machine
 * and release the runtime borrow.
 */
enum dotlottieDotLottieResult dotlottie_state_machine_stop(struct dotlottieDotLottieStateMachine *sm);

/**
 * Destroy the state machine and release the runtime borrow
 *
 * After calling this, the state machine pointer is invalid and the runtime
 * can be used again.
 *
 * # Safety
 * - State machine pointer must be valid
 * - Must not use state machine pointer after this call
 */
void dotlottie_state_machine_release(struct dotlottieDotLottieStateMachine *sm);

/**
 * Tick the state machine (advances animation by `dt` milliseconds and processes state logic).
 *
 * If `rendered` is non-null, writes `true` when a new frame was rendered
 * and `false` when the frame was unchanged.
 */
enum dotlottieDotLottieResult dotlottie_state_machine_tick(struct dotlottieDotLottieStateMachine *sm,
                                                           float dt,
                                                           bool *rendered);

/**
 * Post a pointer/click event to the state machine
 */
enum dotlottieDotLottieResult dotlottie_state_machine_post_event(struct dotlottieDotLottieStateMachine *sm,
                                                                 const struct dotlottiePlayerEvent *event);

/**
 * Helper functions for posting specific event types
 */
enum dotlottieDotLottieResult dotlottie_state_machine_post_click(struct dotlottieDotLottieStateMachine *sm,
                                                                 float x,
                                                                 float y);

enum dotlottieDotLottieResult dotlottie_state_machine_post_pointer_down(struct dotlottieDotLottieStateMachine *sm,
                                                                        float x,
                                                                        float y);

enum dotlottieDotLottieResult dotlottie_state_machine_post_pointer_up(struct dotlottieDotLottieStateMachine *sm,
                                                                      float x,
                                                                      float y);

enum dotlottieDotLottieResult dotlottie_state_machine_post_pointer_move(struct dotlottieDotLottieStateMachine *sm,
                                                                        float x,
                                                                        float y);

enum dotlottieDotLottieResult dotlottie_state_machine_post_pointer_enter(struct dotlottieDotLottieStateMachine *sm,
                                                                         float x,
                                                                         float y);

enum dotlottieDotLottieResult dotlottie_state_machine_post_pointer_exit(struct dotlottieDotLottieStateMachine *sm,
                                                                        float x,
                                                                        float y);

/**
 * Fire a named event input
 */
enum dotlottieDotLottieResult dotlottie_state_machine_fire_event(struct dotlottieDotLottieStateMachine *sm,
                                                                 const char *event_name);

/**
 * Set a numeric input
 */
enum dotlottieDotLottieResult dotlottie_state_machine_set_numeric_input(struct dotlottieDotLottieStateMachine *sm,
                                                                        const char *key,
                                                                        float value);

/**
 * Seed the state machine's PRNG (used by the SetRandom action).
 *
 * Pass fresh entropy per instance for desynchronized randomness, or a fixed
 * value for reproducible runs. Takes effect immediately and is re-applied on
 * every `start()`.
 */
enum dotlottieDotLottieResult dotlottie_state_machine_set_seed(struct dotlottieDotLottieStateMachine *sm,
                                                               uint64_t seed);

/**
 * Set a string input
 */
enum dotlottieDotLottieResult dotlottie_state_machine_set_string_input(struct dotlottieDotLottieStateMachine *sm,
                                                                       const char *key,
                                                                       const char *value);

/**
 * Set a boolean input
 */
enum dotlottieDotLottieResult dotlottie_state_machine_set_boolean_input(struct dotlottieDotLottieStateMachine *sm,
                                                                        const char *key,
                                                                        bool value);

/**
 * Get a numeric input value
 */
enum dotlottieDotLottieResult dotlottie_state_machine_get_numeric_input(struct dotlottieDotLottieStateMachine *sm,
                                                                        const char *key,
                                                                        float *result);

/**
 * Get a string input value.
 *
 * # Parameters
 * - `sm`: Pointer to the StateMachineEngine instance
 * - `key`: Null-terminated C string with the input key
 * - `buffer`: Buffer to store the value, or NULL to query required size
 * - `size_out`: Pointer to receive the required buffer size (including null terminator)
 *
 * # Returns
 * - `DotLottieResult::Success` on success
 * - `DotLottieResult::FeatureNotEnabled` if built without the `state-machines` feature
 * - `DotLottieResult::InvalidParameter` if the input doesn't exist or pointers are invalid
 */
enum dotlottieDotLottieResult dotlottie_state_machine_get_string_input(struct dotlottieDotLottieStateMachine *sm,
                                                                       const char *key,
                                                                       char *buffer,
                                                                       uintptr_t *size_out);

/**
 * Get a boolean input value
 */
enum dotlottieDotLottieResult dotlottie_state_machine_get_boolean_input(struct dotlottieDotLottieStateMachine *sm,
                                                                        const char *key,
                                                                        bool *result);

/**
 * Get current state name.
 *
 * # Parameters
 * - `sm`: Pointer to the StateMachineEngine instance
 * - `buffer`: Buffer to store the state name, or NULL to query required size
 * - `size_out`: Pointer to receive the required buffer size (including null terminator)
 *
 * # Returns
 * - `DotLottieResult::Success` on success
 * - `DotLottieResult::FeatureNotEnabled` if built without the `state-machines` feature
 * - `DotLottieResult::InvalidParameter` if pointer is invalid
 */
enum dotlottieDotLottieResult dotlottie_state_machine_get_current_state(struct dotlottieDotLottieStateMachine *sm,
                                                                        char *buffer,
                                                                        uintptr_t *size_out);

/**
 * Get state machine status.
 *
 * # Parameters
 * - `sm`: Pointer to the StateMachineEngine instance
 * - `buffer`: Buffer to store the status, or NULL to query required size
 * - `size_out`: Pointer to receive the required buffer size (including null terminator)
 *
 * # Returns
 * - `DotLottieResult::Success` on success
 * - `DotLottieResult::FeatureNotEnabled` if built without the `state-machines` feature
 * - `DotLottieResult::InvalidParameter` if pointer is invalid
 */
enum dotlottieDotLottieResult dotlottie_state_machine_get_status(struct dotlottieDotLottieStateMachine *sm,
                                                                 char *buffer,
                                                                 uintptr_t *size_out);

/**
 * Get interaction types for framework setup
 *
 * Returns bit flags indicating which interaction types are needed.
 * Frameworks should register listeners for the returned interaction types.
 */
enum dotlottieDotLottieResult dotlottie_state_machine_get_framework_setup(struct dotlottieDotLottieStateMachine *sm,
                                                                          uint16_t *result);

/**
 * Poll for the next state machine event
 *
 * Returns 1 if an event was retrieved, 0 if no events are available, or -1 on error.
 * String pointers in the event struct are valid until the next poll call.
 *
 * # Example
 * ```c
 * StateMachineEvent event;
 * while (dotlottie_state_machine_poll_event(sm, &event) == 1) {
 *     switch (event.event_type) {
 *         case StateMachineEventType_StateMachineTransition:
 *             // Pointers valid until next poll
 *             printf("Transition: %s -> %s\n",
 *                    event.data.transition.previous_state,
 *                    event.data.transition.new_state);
 *             break;
 *         case StateMachineEventType_StateMachineStateEntered:
 *             printf("Entered: %s\n", event.data.state.state);
 *             break;
 *     }
 * }
 * ```
 */
int32_t dotlottie_state_machine_poll_event(struct dotlottieDotLottieStateMachine *sm,
                                           struct dotlottieStateMachineEvent *event);

/**
 * Poll for the next internal state machine event
 *
 * Returns 1 if an event was retrieved, 0 if no events are available, or -1 on error.
 * The message pointer is valid until the next poll call.
 */
int32_t dotlottie_state_machine_poll_internal_event(struct dotlottieDotLottieStateMachine *sm,
                                                    struct dotlottieStateMachineInternalEvent *event);

/**
 * Get the state machine definition as JSON string.
 *
 * # Parameters
 * - `runtime`: Pointer to the Player instance
 * - `state_machine_id`: Null-terminated C string with the state machine ID
 * - `buffer`: Buffer to store the JSON, or NULL to query required size
 * - `size_out`: Pointer to receive the required buffer size (including null terminator)
 *
 * # Returns
 * - `DotLottieResult::Success` on success
 * - `DotLottieResult::FeatureNotEnabled` if built without the `state-machines` feature
 * - `DotLottieResult::InvalidParameter` if state machine not found or pointers are invalid
 */
enum dotlottieDotLottieResult dotlottie_get_state_machine(struct dotlottiePlayer *runtime,
                                                          const char *state_machine_id,
                                                          char *buffer,
                                                          uintptr_t *size_out);

/**
 * Initialise the Android JVM context required by cpal/rodio for audio output.
 *
 * Must be called once before loading any animation that contains audio.
 * Safe to call multiple times — subsequent calls are ignored by ndk-context.
 *
 * # Arguments
 * * `vm`  - pointer to the `JavaVM` struct (cast from `JavaVM*`)
 * * `ctx` - JNI global reference to an `android.content.Context` object
 */
void dotlottie_init_android(void *vm, void *ctx);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* DOTLOTTIE_PLAYER_H */
